# Generated by Django 3.1.7 on 2021-03-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.IntegerField(blank=True, default=0, max_length=5),
        ),
    ]
